
name: publish
on: [push]
jobs:
publish-hello-d-o-1:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Login to GitHub Container Registry
uses: docker/login-action@v1
with:
registry: ghcr.io
username: ${{ github.actor }}
password: ${{ secrets.GITHUB_TOKEN }}
- name: Build the do1 Docker image
run: |
       docker build . --tag ghcr.io/chris-f-anderson/hello-d-o-1:latest
       docker run ghcr.io/chris-f-anderson/hello-d-o-1:latest
       docker push ghcr.io/chris-f-anderson/hello-d-o-1:latest
